[env]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "xv7-boot"
ESP = "target/esp"
QEMU_X86_64 = "qemu-system-x86_64"
QEMU_X86_64_OPT = '''
    -drive if=pflash,format=raw,file=.qemu/OVMF-pure-efi.fd,readonly=on
    -device isa-debug-exit,iobase=0xf4,iosize=0x04
    -serial stdio
    -m 256M
    -net none
'''

[tasks.xbuild]
command = "cargo"
args = ["xbuild"]

[tasks.member-xbuild]
command = "cargo"
args = ["make", "xbuild"]

[tasks.compose-esp]
workspace = false
dependencies = ["member-xbuild"]
script_runner = "@shell"
script = [
'''
mkdir -p ${ESP}/EFI/Boot
cp target/x86_64-unknown-uefi/debug/xv7-bootloader-uefi.efi ${ESP}/EFI/Boot/BootX64.efi
mkdir -p ${ESP}/EFI/xv7
cp target/x86_64/debug/xv7-kernel ${ESP}/EFI/xv7/kernel
rust-objdump -d ${ESP}/EFI/xv7/kernel > ${ESP}/EFI/xv7/kernel.asm || true
'''
]

[tasks.qemu]
workspace = false
dependencies = ["compose-esp"]
script_runner = "@shell"
script = [
'''
${QEMU_X86_64} ${QEMU_X86_64_OPT} \
    -drive format=raw,file=fat:rw:${ESP}
'''
]

[tasks.qemu-kvm]
workspace = false
dependencies = ["compose-esp"]
script_runner = "@shell"
script = [
'''
${QEMU_X86_64} ${QEMU_X86_64_OPT} \
    -drive format=raw,file=fat:rw:${ESP} \
    -enable-kvm
'''
]

[tasks.doc]
workspace = false
command = "cargo"
args = ["doc", "--no-deps", "--open"]

[tasks.compose-image]
workspace = false
dependencies = ["member-xbuild"]
script_runner = "@rust"
script = { file = "compose.rs" }
