[env]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "xv7-boot"

[tasks.xbuild]
command = "cargo"
args = ["xbuild"]

[tasks.member-xbuild]
command = "cargo"
args = ["make", "xbuild"]

[tasks.qemu]
workspace = false
dependencies = ["member-xbuild"]
script = [
'''
mkdir -p target/esp/EFI/BOOT
cp target/x86_64-unknown-uefi/debug/xv7-bootloader-uefi.efi target/esp/EFI/BOOT/BOOTX64.EFI
mkdir -p target/esp/EFI/xv7
cp target/x86_64-unknown-none/debug/xv7-kernel target/esp/EFI/xv7/kernel
objdump -d target/esp/EFI/xv7/kernel > target/esp/EFI/xv7/kernel.asm
qemu-system-x86_64 \
    -drive if=pflash,format=raw,file=.qemu/OVMF-pure-efi.fd,readonly=on \
    -drive format=raw,file=fat:rw:target/esp \
    -device isa-debug-exit,iobase=0xf4,iosize=0x04 \
    -serial stdio \
    -m 256M
'''
]

[tasks.compose-image]
workspace = false
dependencies = ["member-xbuild"]
script_runner = "@rust"
script = { file = "compose.rs" }
