[package]
name = "xv7-bootloader-uefi"
version = "0.1.0"
authors = ["imtsuki <me@qjx.app>"]
description = "XV7 UEFI Bootloader"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = "0.4.3"
uefi-services = "0.2.1"
x86_64 = "0.8.3"
xmas-elf = "0.7.0"
log = { version = "0.4.8", default-features = false }
chrono = { version = "0.4.10", default-features = false }
bootinfo = { path = "../xv7-bootinfo", package = "xv7-bootinfo" }
